// data/organizations.js
export const organizations = [
    {
      id: 1,
      name: 'Clean Water Foundation',
      category: 'Environment',
      wallet: '0x1234ABCD5678EFGH',
      description: 'A foundation working on providing clean water to underprivileged communities.',
      image: 'https://source.unsplash.com/random/300x200/?water',
      projects: ['Project Clean Lake', 'Community Wells'],
      milestones: ['Raised $1M for clean water'],
    },
    {
      id: 2,
      name: 'Feed the Hungry',
      category: 'Poverty',
      wallet: '0x1234EFGH5678ABCD',
      description: 'Providing meals to impoverished communities across the globe.',
      image: 'https://source.unsplash.com/random/300x200/?food',
      projects: ['Meal Program for Kids', 'Community Kitchens'],
      milestones: ['Served 10M meals worldwide'],
    },
    {
      id: 3,
      name: 'Tech for Good',
      category: 'Education',
      wallet: '0x5678ABCD1234EFGH',
      description: 'Bringing tech education to underserved communities.',
      image: 'https://source.unsplash.com/random/300x200/?education',
      projects: ['Tech Bootcamps', 'Coding for Girls'],
      milestones: ['Trained 500+ students in tech'],
    },
    {
      id: 4,
      name: 'Green Earth Initiative',
      category: 'Environment',
      wallet: '0xABCD1234EFGH5678',
      description: 'An initiative to reduce carbon emissions and promote renewable energy.',
      image: 'https://source.unsplash.com/random/300x200/?forest',
      projects: ['Tree Planting Drives', 'Solar Panel Installation'],
      milestones: ['Planted 1M trees globally'],
    },
    {
      id: 5,
      name: 'Healthcare for All',
      category: 'Health',
      wallet: '0xEFGH5678ABCD1234',
      description: 'Ensuring that all individuals have access to basic healthcare services.',
      image: 'https://source.unsplash.com/random/300x200/?healthcare',
      projects: ['Mobile Health Clinics', 'Vaccination Drives'],
      milestones: ['Provided healthcare to 100K+ patients'],
    },
    {
      id: 6,
      name: 'Literacy for Life',
      category: 'Education',
      wallet: '0x1234ABCD5678EFGH',
      description: 'Promoting literacy and education in developing nations.',
      image: 'https://source.unsplash.com/random/300x200/?books',
      projects: ['Book Donation Program', 'Adult Literacy Classes'],
      milestones: ['Distributed 50K+ books'],
    },
    {
      id: 7,
      name: 'Homes for the Homeless',
      category: 'Poverty',
      wallet: '0x5678EFGH1234ABCD',
      description: 'Building homes and shelters for homeless people.',
      image: 'https://source.unsplash.com/random/300x200/?home',
      projects: ['Urban Shelters', 'Emergency Housing'],
      milestones: ['Built 10K+ homes for the homeless'],
    },
    {
      id: 8,
      name: 'Clean Oceans Initiative',
      category: 'Environment',
      wallet: '0xABCD5678EFGH1234',
      description: 'Cleaning up oceans and protecting marine life.',
      image: 'https://source.unsplash.com/random/300x200/?ocean',
      projects: ['Ocean Cleanup Drives', 'Coral Reef Restoration'],
      milestones: ['Removed 50 tons of ocean plastic waste'],
    },
    {
      id: 9,
      name: 'Women in Tech',
      category: 'Education',
      wallet: '0xEFGH1234ABCD5678',
      description: 'Empowering women in technology through mentorship and training programs.',
      image: 'https://source.unsplash.com/random/300x200/?women',
      projects: ['Tech Mentorship Program', 'Women in Coding Bootcamp'],
      milestones: ['Supported 200+ women in tech careers'],
    },
    {
      id: 10,
      name: 'Save the Rainforest',
      category: 'Environment',
      wallet: '0x1234EFGH5678ABCD',
      description: 'Protecting rainforests and biodiversity around the globe.',
      image: 'https://source.unsplash.com/random/300x200/?rainforest',
      projects: ['Rainforest Conservation', 'Wildlife Protection'],
      milestones: ['Saved 10K hectares of rainforest land'],
    },
    {
      id: 11,
      name: 'Medical Supplies for All',
      category: 'Health',
      wallet: '0x5678ABCD1234EFGH',
      description: 'Providing free medical supplies to those in need.',
      image: 'https://source.unsplash.com/random/300x200/?medicine',
      projects: ['Medical Kit Distribution', 'Health Aid Program'],
      milestones: ['Distributed 100K medical kits'],
    },
    {
      id: 12,
      name: 'Teach the Future',
      category: 'Education',
      wallet: '0xABCD5678EFGH1234',
      description: 'Equipping teachers with modern skills to educate the next generation.',
      image: 'https://source.unsplash.com/random/300x200/?teaching',
      projects: ['Teacher Training Workshops', 'Digital Education Program'],
      milestones: ['Trained 1K+ teachers in new education methodologies'],
    },
    {
      id: 13,
      name: 'Farmers First',
      category: 'Poverty',
      wallet: '0xEFGH1234ABCD5678',
      description: 'Supporting farmers by providing resources and training.',
      image: 'https://source.unsplash.com/random/300x200/?farming',
      projects: ['Sustainable Farming', 'Farm Equipment Donation'],
      milestones: ['Helped 500+ farmers increase yields'],
    },
    {
      id: 14,
      name: 'Health is Wealth',
      category: 'Health',
      wallet: '0x1234ABCD5678EFGH',
      description: 'Promoting healthy lifestyles and mental well-being.',
      image: 'https://source.unsplash.com/random/300x200/?fitness',
      projects: ['Mental Health Awareness', 'Fitness Programs'],
      milestones: ['Reached 100K+ individuals in mental health initiatives'],
    },
    {
      id: 15,
      name: 'Save the Wildlife',
      category: 'Environment',
      wallet: '0x5678EFGH1234ABCD',
      description: 'Working to protect endangered wildlife species.',
      image: 'https://source.unsplash.com/random/300x200/?wildlife',
      projects: ['Wildlife Sanctuaries', 'Anti-Poaching Programs'],
      milestones: ['Protected 50 endangered species'],
    },
    {
      id: 16,
      name: 'Brighter Tomorrow',
      category: 'Education',
      wallet: '0xABCD1234EFGH5678',
      description: 'Creating brighter futures through education and mentoring.',
      image: 'https://source.unsplash.com/random/300x200/?future',
      projects: ['Youth Mentorship', 'After-School Programs'],
      milestones: ['Guided 200+ students to higher education'],
    },
    {
      id: 17,
      name: 'Feeding the Future',
      category: 'Poverty',
      wallet: '0xEFGH5678ABCD1234',
      description: 'Providing nutritious meals to children in need.',
      image: 'https://source.unsplash.com/random/300x200/?meals',
      projects: ['School Meal Programs', 'Community Food Banks'],
      milestones: ['Served 500K meals to children worldwide'],
    },
    {
      id: 18,
      name: 'Green Energy Solutions',
      category: 'Environment',
      wallet: '0x1234EFGH5678ABCD',
      description: 'Promoting renewable energy and sustainable practices.',
      image: 'https://source.unsplash.com/random/300x200/?solar',
      projects: ['Solar Panel Distribution', 'Wind Energy Farms'],
      milestones: ['Powered 10K+ homes with renewable energy'],
    },
    {
      id: 19,
      name: 'Global Education Fund',
      category: 'Education',
      wallet: '0x5678ABCD1234EFGH',
      description: 'Providing scholarships and education resources globally.',
      image: 'https://source.unsplash.com/random/300x200/?scholarship',
      projects: ['Global Scholarship Program', 'School Resource Donations'],
      milestones: ['Awarded 1K+ scholarships to students'],
    },
    {
      id: 20,
      name: 'Emergency Aid Network',
      category: 'Health',
      wallet: '0xABCD5678EFGH1234',
      description: 'Providing emergency aid and disaster relief globally.',
      image: 'https://source.unsplash.com/random/300x200/?emergency',
      projects: ['Disaster Relief Efforts', 'Medical Aid Shipments'],
      milestones: ['Responded to 50+ global disasters'],
    }
  ];
  